# Created by Jekyll Writer
title: 'awesome '
author: qn'lz
description: >
  This theme is disigned based on Mailbox Blog, and licensed under MIT. This
  theme is also default theme for new site created by Jekyll Writer.
permalink: '/:year/:month/:day/:title/'
paginate: 10
paginate_path: '/page/:num/'
twitter_username: qnlz
github_username: qnlz
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /blog
